---
- name: install git
  shell: apt install git -y


- name: check containers exists
  stat: 
    path: "{{ frigg_repo_dir}}"
  register: frigg_dir

- name: check it is a git repo
  stat: 
    path: "{{ frigg_repo_dir}}/.git/config"
  register: frigg_git


- name: delete dir
  shell: rm -rf "{{ frigg_repo_dir}}"
  when: frigg_dir.stat.exists and frigg_git.stat.exists == false

- name: stop containers 
  shell: docker-compose -f "{{ frigg_repo_dir }}/{{ item }}/docker-compose.yml" down
  ignore_errors: true
  with_items:
    - bind
    - redis
    - gitlab
    - registry
    - traefik
  when: frigg_dir.stat.exists 

- name: prune containers and networks
  shell: docker {{ item }} prune -f 
  ignore_errors: true
  with_items:
    - container
    - network 

- name: clone Kenevist/frigg repository
  git: 
    repo: https://github.com/Kenevist/frigg.git
    dest: "{{ frigg_repo_dir }}"
    update: yes

#- name: monkey patch for now
#  shell: sed s/${PASSWORD}/5iveSe7en/ "{{ frigg_repo_dir }}/gitlab/docker-compose.yml"

- name: Create a network
  shell: docker network create {{ item }}
  with_items:
    - backend
    - web

- name: run docker-compose files
  shell: docker-compose -f "{{ frigg_repo_dir }}/{{ item }}/docker-compose.yml" up --build -d 
  with_items:
    - bind
    - redis
#    - gitlab
    - registry
    - traefik

- name: run gitlab docker-compose gitlab
  shell: env && cd {{ frigg_repo_dir }}/gitlab && docker-compose up --build -d
  environment:
    GITLAB_DB_USER: "jafar"
    GITLAB_DB_PASS: "jafarjafar"
    GITLAB_DB_NAME: "jafardb"
