---
- name: install git
  shell: apt install git -y

- name: stop containers 
  shell: docker-compose -f {{ frigg_repo_dir }}/{{ item }}/docker-compose.yml down
  ignore_errors: true
  with_items:
    - bind
    - redis
    - gitlab
    - traefik

- name: prune containers and networks
  shell: docker {{ item }} prune -f 
  ignore_errors: true
  with_items:
    - container
    - network 

- name: clone Kenevist/frigg repository
  git: 
    repo: https://github.com/Kenevist/frigg.git
    dest: {{ frigg_repo_dir }}
    update: yes

- name: monkey patch for now
  shell: sed s/{$PASSWORD}/5iveSe7en/ {{ frigg_repo_dir }}/gitlab/docker-compose.yml

- name: Create a network
  docker_network:
    name: backend


- name: run docker-compose files
  shell: docker-compose -f {{ frigg_repo_dir }}/{{ item }}/docker-compose.yml up --build -d 
  with_items:
    - bind
    - redis
    - gitlab
    - traefik

