frigg_repo_dir: /containers


git_repo_src: "https://github.com/iamvee/frigg.git"
git_repo_dest: "/tmp/repositories/frigg/"
git_repo_version: "jinja-templates"

template_suffix: "j2"
template_file: ".{{ template_suffix }}"

build_path: "/containers"


templated_file_dest: "/root/build/docker-compose.yml"


traefik_defaults:
  domain: "kenevist.ir"
  email: "kenevist@gmail.com"

whoami_defaults:
  domain: "whoami.kenevist.ir"

gitlab_defaults:
  image:
    name: "sameersbn/gitlab"
    tag: "12.4.0"    

  ports:
    http: 10080
    ssh: 10022

  host: "git.kenevist.ir"

  db:
    name: "name" 
    username: "gitlab"
    password: "password"

  email:
    email: "notifications@example.com"
    reply_to: "noreply@example.com"
    incoming: "reply@example.com"

